# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-02-26 14:08+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: C:\xliff_validator\src\gui\file_handler.py:14
msgid "Select an XLIFF File"
msgstr ""

#: C:\xliff_validator\src\gui\file_handler.py:16
msgid "XLIFF Files (*.xlf *.xliff);;All Files (*)"
msgstr ""

#: C:\xliff_validator\src\gui\file_handler.py:24
msgid "Error"
msgstr ""

#: C:\xliff_validator\src\gui\file_handler.py:24
#: C:\xliff_validator\src\gui\file_handler.py:25
msgid "The selected file does not exist."
msgstr ""

#: C:\xliff_validator\src\gui\file_handler.py:30
msgid "Invalid File"
msgstr ""

#: C:\xliff_validator\src\gui\file_handler.py:30
msgid "Please select a valid XLIFF file (.xlf or .xliff)."
msgstr ""

#: C:\xliff_validator\src\gui\home_screen.py:18
msgid "Welcome to XLIFF Validator"
msgstr ""

#: C:\xliff_validator\src\gui\home_screen.py:24
msgid "Validate XLIFF"
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:14
msgid "XLIFF Validator"
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:37
msgid "File"
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:41
msgid "Validate XLIFF File"
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:46
msgid "Exit"
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:60
msgid "User closed aplication."
msgstr ""

#: C:\xliff_validator\src\gui\main_window.py:64
msgid "User started application"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:25
#: C:\xliff_validator\src\gui\validator_screen.py:68
msgid "Open XLIFF File"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:31
msgid "XLIFF Validation Report"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:40
msgid "Export to Excel"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:47
msgid "Export to Database"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:54
msgid "Back to Home"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:64
msgid "XLIFF Files (*.xliff *.xml)"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:73
msgid "No file selected."
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:88
#: C:\xliff_validator\src\logic\excel_exporter.py:32
msgid "Segment ID"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:89
#: C:\xliff_validator\src\logic\excel_exporter.py:33
msgid "Source"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:90
#: C:\xliff_validator\src\logic\excel_exporter.py:34
msgid "Target"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:91
#: C:\xliff_validator\src\logic\excel_exporter.py:35
msgid "QA Status"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:115
#: C:\xliff_validator\src\logic\qa_checker.py:111
msgid "Correct"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:117
#: C:\xliff_validator\src\logic\qa_checker.py:94
msgid "Untranslated segment"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:119
#: C:\xliff_validator\src\logic\qa_checker.py:100
msgid "Source in target"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:121
#: C:\xliff_validator\src\logic\qa_checker.py:97
msgid "Source missing"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:123
#: C:\xliff_validator\src\logic\qa_checker.py:103
msgid "Mismatch/missing tag"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:125
#: C:\xliff_validator\src\logic\qa_checker.py:106
msgid "Mismatch/missing number"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:127
#: C:\xliff_validator\src\logic\qa_checker.py:109
msgid "Pseudotranslated"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:137
#: C:\xliff_validator\src\gui\validator_screen.py:140
msgid "Excel confirmation"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:144
#: C:\xliff_validator\src\gui\validator_screen.py:167
msgid "No validation results to export."
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:157
#: C:\xliff_validator\src\gui\validator_screen.py:162
msgid "Database confirmation"
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:172
#: C:\xliff_validator\src\logic\database_exporter.py:45
#: C:\xliff_validator\src\logic\database_exporter.py:46
#: C:\xliff_validator\src\logic\database_exporter.py:48
msgid "Validation results exported to database successfully."
msgstr ""

#: C:\xliff_validator\src\gui\validator_screen.py:172
#: C:\xliff_validator\src\logic\excel_exporter.py:56
#: C:\xliff_validator\src\logic\excel_exporter.py:57
msgid "Excel export completed successfully!"
msgstr ""

#: C:\xliff_validator\src\logic\database_exporter.py:10
msgid "MySQL import error: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\database_exporter.py:53
#: C:\xliff_validator\src\logic\database_exporter.py:54
#: C:\xliff_validator\src\logic\database_exporter.py:56
msgid "Connector error: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\database_exporter.py:61
#: C:\xliff_validator\src\logic\database_exporter.py:62
#: C:\xliff_validator\src\logic\database_exporter.py:64
msgid "Generic error in database exporter file: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:15
msgid "Save Excel File"
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:17
msgid "Excel Files (*.xlsx)"
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:31
msgid "Segment Number"
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:62
#: C:\xliff_validator\src\logic\excel_exporter.py:63
msgid "â Error: File path not found."
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:68
#: C:\xliff_validator\src\logic\excel_exporter.py:69
msgid "â Error: File is open. Please close it and try again."
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:74
#: C:\xliff_validator\src\logic\excel_exporter.py:75
msgid "â Value Error: {ve}"
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:80
#: C:\xliff_validator\src\logic\excel_exporter.py:81
msgid "â IOError: Problem writing to file."
msgstr ""

#: C:\xliff_validator\src\logic\excel_exporter.py:86
#: C:\xliff_validator\src\logic\excel_exporter.py:87
msgid "â Unexpected Error: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:37
msgid "Segments extracted with internal tags successfully."
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:42
#: C:\xliff_validator\src\logic\qa_checker.py:43
msgid "Error: The XLIFF file is corrupted or unreadable."
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:46
#: C:\xliff_validator\src\logic\qa_checker.py:47
msgid "Error: "
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:114
#: C:\xliff_validator\src\logic\qa_checker.py:115
msgid "Error on QA validation rules: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:128
#: C:\xliff_validator\src\logic\qa_checker.py:129
msgid "Error checking mismatched tags: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:142
#: C:\xliff_validator\src\logic\qa_checker.py:143
msgid "Error checking mismatched numbers: {e}"
msgstr ""

#: C:\xliff_validator\src\logic\qa_checker.py:152
#: C:\xliff_validator\src\logic\qa_checker.py:153
msgid "Error checking pseudotranslated segments: {e}"
msgstr ""
